[theme]
primaryColor = "#00ADB5"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#222831"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false